---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopeinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopeinstances/finalizers
  verbs:
  - update
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopeinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
